// Adapted to .NET Framework Release Version by M.H.
//
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Drawing.Drawing2D;

namespace imgFormat
{
   

    // A C# Image Converter By George Anescu 
    // http://www.codeproject.com/cs/media/imagconvert.asp
    //

    /// 
    /// Form1 is the main platform for demostrating the graphics file transformation functions.
    /// 
    public class Form1 : System.Windows.Forms.Form
    {
  
        /// The Container generated by C# wizard.
        private System.ComponentModel.Container components;
        /// 
        /// The PictureBox where the loaded picture previews.
        private System.Windows.Forms.PictureBox m_pictureBox;
        /// 
        /// The reference that holds the opened picture.
        private Bitmap m_bitmap;
        /// 
        /// The width of PictureBox that determines whether the picture would be adjusted to the PictureBox size.
        private int m_width0;
        private ToolStripButton m_btnOpen;
        private ToolStripButton m_btnSaveAs;
        private ToolStrip toolStrip1;
        private ToolStripButton m_btnExit;
        private ToolStripButton m_btnZip;
        /// 
        /// The height of PictureBox that determines whether the picture would be adjusted to the PictureBox size.
        private int m_height0;

        /// 
        /// The main windows which the application launches.
        /// 
        public Form1()
        {
            //
            // Required for Windows Form Designer support
            //
            InitializeComponent();
            //Other Initializations
            
            m_width0 = m_pictureBox.Size.Width;
            m_height0 = m_pictureBox.Size.Height;
    

            
        }
        /// 
        /// Clean up any resources being used.
        ///
        //protected override void Dispose(bool disposing)
        //{
        //    try
        //    {
        //        if (disposing)
        //        {
        //            // Release the managed resources you added in this derived class here.
        //            //m_cmbSaveAs.Dispose();
        //            //m_cmbOpen.Dispose();
                    
        //            m_pictureBox.Dispose();
        //            m_btnSaveAs.Dispose();
        //            m_btnOpen.Dispose();
        //            toolStrip1.Dispose();
        //            components.Dispose();
                    
                   
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        MessageBox.Show(ex.ToString());
        //    }
        //    finally
        //    {
        //        // Call Dispose on your base class.
        //        base.Dispose(disposing);
        //    }
        //}

        /// 
        /// Initialize the components/resources insides the windows.
        ///
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.m_btnOpen = new System.Windows.Forms.ToolStripButton();
            this.m_btnSaveAs = new System.Windows.Forms.ToolStripButton();
            this.m_btnZip = new System.Windows.Forms.ToolStripButton();
            this.m_btnExit = new System.Windows.Forms.ToolStripButton();
            this.m_pictureBox = new System.Windows.Forms.PictureBox();
            this.toolStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_pictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // toolStrip1
            // 
            this.toolStrip1.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.m_btnOpen,
            this.m_btnSaveAs,
            this.m_btnZip,
            this.m_btnExit});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(539, 41);
            this.toolStrip1.TabIndex = 3;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // m_btnOpen
            // 
            this.m_btnOpen.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.m_btnOpen.Image = ((System.Drawing.Image)(resources.GetObject("m_btnOpen.Image")));
            this.m_btnOpen.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.m_btnOpen.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.m_btnOpen.Name = "m_btnOpen";
            this.m_btnOpen.Size = new System.Drawing.Size(38, 38);
            this.m_btnOpen.ToolTipText = "Open Image File";
            this.m_btnOpen.Click += new System.EventHandler(this.btnOpen_Click);
            // 
            // m_btnSaveAs
            // 
            this.m_btnSaveAs.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.m_btnSaveAs.Image = ((System.Drawing.Image)(resources.GetObject("m_btnSaveAs.Image")));
            this.m_btnSaveAs.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.m_btnSaveAs.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.m_btnSaveAs.Name = "m_btnSaveAs";
            this.m_btnSaveAs.Size = new System.Drawing.Size(38, 38);
            this.m_btnSaveAs.ToolTipText = "Save As ...";
            this.m_btnSaveAs.Click += new System.EventHandler(this.btnSaveAs_Click);
            // 
            // m_btnZip
            // 
            this.m_btnZip.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.m_btnZip.Image = global::imgFormat.Properties.Resources.compress_icon;
            this.m_btnZip.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.m_btnZip.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.m_btnZip.Name = "m_btnZip";
            this.m_btnZip.Size = new System.Drawing.Size(36, 38);
            this.m_btnZip.Text = "toolStripButton2";
            this.m_btnZip.ToolTipText = "Compress image";
            this.m_btnZip.Click += new System.EventHandler(this.m_btnZip_Click);
            // 
            // m_btnExit
            // 
            this.m_btnExit.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.m_btnExit.Image = global::imgFormat.Properties.Resources.Sign_Error_icon;
            this.m_btnExit.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.m_btnExit.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.m_btnExit.Name = "m_btnExit";
            this.m_btnExit.Size = new System.Drawing.Size(36, 38);
            this.m_btnExit.ToolTipText = "Exit";
            this.m_btnExit.Click += new System.EventHandler(this.m_btnExit_Click);
            // 
            // m_pictureBox
            // 
            this.m_pictureBox.BackColor = System.Drawing.Color.LavenderBlush;
            this.m_pictureBox.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.m_pictureBox.Location = new System.Drawing.Point(12, 44);
            this.m_pictureBox.Name = "m_pictureBox";
            this.m_pictureBox.Size = new System.Drawing.Size(515, 311);
            this.m_pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.m_pictureBox.TabIndex = 2;
            this.m_pictureBox.TabStop = false;
            // 
            // Form1
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(7, 19);
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.ClientSize = new System.Drawing.Size(539, 367);
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.m_pictureBox);
            this.Font = new System.Drawing.Font("Times New Roman", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Image Convertor";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        /// 
        /// The function triggered by 'Save As' Button event. The SaveFileDialog will launch after 'Save As'
        /// button being clicked, assign the extension according to m_cmbSaveAs instance holds, and then save
        /// to the new formatted file.
        ///
        protected void btnSaveAs_Click(object sender, System.EventArgs e)
        {
            SaveFileDialog sfd = new SaveFileDialog();
            sfd.Title = "Save Image As";
            sfd.OverwritePrompt = true;
            sfd.CheckPathExists = true;
            sfd.Filter = "Jpeg Images |*.jpg|Bitmap Images|*.bmp|PNG Images|*.png|Tiff Images|*.tif|All files (*.*)|*.*";
            sfd.ShowHelp = true;
            if (sfd.ShowDialog() == DialogResult.OK)
            {
                string strFileName = sfd.FileName;
                //MessageBox.Show(sfd.FileName.Substring(sfd.FileName.IndexOf('.'),4));
                switch (sfd.FileName.Substring(sfd.FileName.IndexOf('.'), 4))
                {
                    case ".png":
                        m_bitmap.Save(strFileName, ImageFormat.Png);
                        break;
     
                    case ".bmp":
                        m_bitmap.Save(strFileName, ImageFormat.Bmp);
                        break;

                    case ".jpg":
                        m_bitmap.Save(strFileName, ImageFormat.Jpeg);
                        break;

                    case ".gif":
                        m_bitmap.Save(strFileName, ImageFormat.Gif);
                        break;

                    case ".tif":
                        m_bitmap.Save(strFileName, ImageFormat.Tiff);
                        break;
                }
                this.Text = "Image Converter: " + strFileName;
            }
        }

        /// 
        /// The function triggered by 'Open' Button event. The OpenFileDialog will launch after 'Open'
        /// button being clicked to open graphics file(s) with the extension that m_cmbOpen instance 
        /// holds. After the file open successfully, the preview box will show the thumbnail about 
        /// what picture looks like; and enable the 'Save As' button.
        /// 
        protected void btnOpen_Click(object sender, System.EventArgs e)
        {
            OpenFileDialog ofd = new OpenFileDialog();
            //ofd.Filter = m_cmbOpen.Text + "|" + m_cmbOpen.Text;
            ofd.Filter = "Image files (*.jpg, *.jpeg, *.jpe, *.jfif, *.png,*.bmp) | *.jpg; *.jpeg; *.jpe; *.jfif; *.png; *.bmp";
            string filter = ofd.Filter;
            ofd.InitialDirectory = System.Environment.CurrentDirectory;
            ofd.Title = "Open Image File";
            ofd.ShowHelp = true;
            if (ofd.ShowDialog() == DialogResult.OK)
            {
                string strFileName = ofd.FileName;
                m_bitmap = new Bitmap(strFileName);
                if (m_bitmap.Width > m_bitmap.Height)
                {
                    //Keep the width
                    m_pictureBox.Width = m_width0;

                    m_pictureBox.Height = (int)((double)m_bitmap.Height * m_width0 / m_bitmap.Width);
                }
                else
                {
                    //Keep the height
                    m_pictureBox.Height = m_height0;
                    m_pictureBox.Width = (int)((double)m_bitmap.Width * m_height0 / m_bitmap.Height);
         
                }
                m_pictureBox.Image = m_bitmap;
                this.Text = "Image Converter: " + strFileName;
                m_btnSaveAs.Enabled = true;
            }
        }

        private void m_btnExit_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void m_btnZip_Click(object sender, EventArgs e)
        {
             FolderBrowserDialog fbd = new FolderBrowserDialog();
            //ofd.Filter = m_cmbOpen.Text + "|" + m_cmbOpen.Text;
            //ofd.Filter = "Image files (*.bmp) | *.bmp;";
            //string filter = ofd.Filter;
            //ofd.InitialDirectory = System.Environment.CurrentDirectory;
            //ofd.Title = "Open Image File";
            //ofd.ShowHelp = true;
            if (fbd.ShowDialog() == DialogResult.OK)
            {
                string strFileName = fbd.SelectedPath;
                string value = "";
                if (Form1.InputBox("New document", "New document name:", ref value) == DialogResult.OK)
                {
                    strFileName = strFileName + value +".bmp";
                }
			
                if(CompressJPEGImage(m_bitmap,strFileName))
                    MessageBox.Show("success");
                else
                    MessageBox.Show("error please try again");
                
               
            }
        }



        public bool CompressJPEGImage(Bitmap bmp1, string tempImgNameWithPath)
        {
            ImageCodecInfo jgpEncoder = GetEncoder(ImageFormat.Jpeg);

            // for the Quality parameter category.
            System.Drawing.Imaging.Encoder myEncoder = System.Drawing.Imaging.Encoder.Quality;

            EncoderParameters myEncoderParameters = new EncoderParameters(1);
            EncoderParameter myEncoderParameter = new EncoderParameter(myEncoder, 75L);
            myEncoderParameters.Param[0] = myEncoderParameter;
            try
            {
                bmp1.Save(tempImgNameWithPath, jgpEncoder, myEncoderParameters);
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        private ImageCodecInfo GetEncoder(ImageFormat format)
        {

            ImageCodecInfo[] codecs = ImageCodecInfo.GetImageDecoders();

            foreach (ImageCodecInfo codec in codecs)
            {
                if (codec.FormatID == format.Guid)
                {
                    return codec;
                }
            }
            return null;
        }

        public static DialogResult InputBox(string title, string promptText, ref string value)
        {
            Form form = new Form();
            Label label = new Label();
            TextBox textBox = new TextBox();
            Button buttonOk = new Button();
            Button buttonCancel = new Button();

            form.Text = title;
            label.Text = promptText;
            textBox.Text = value;

            buttonOk.Text = "OK";
            buttonCancel.Text = "Cancel";
            buttonOk.DialogResult = DialogResult.OK;
            buttonCancel.DialogResult = DialogResult.Cancel;

            label.SetBounds(9, 20, 372, 13);
            textBox.SetBounds(12, 36, 372, 20);
            buttonOk.SetBounds(228, 72, 75, 23);
            buttonCancel.SetBounds(309, 72, 75, 23);

            label.AutoSize = true;
            textBox.Anchor = textBox.Anchor | AnchorStyles.Right;
            buttonOk.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            buttonCancel.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;

            form.ClientSize = new Size(396, 107);
            form.Controls.AddRange(new Control[] { label, textBox, buttonOk, buttonCancel });
            form.ClientSize = new Size(Math.Max(300, label.Right + 10), form.ClientSize.Height);
            form.FormBorderStyle = FormBorderStyle.FixedDialog;
            form.StartPosition = FormStartPosition.CenterScreen;
            form.MinimizeBox = false;
            form.MaximizeBox = false;
            form.AcceptButton = buttonOk;
            form.CancelButton = buttonCancel;

            DialogResult dialogResult = form.ShowDialog();
            value = textBox.Text;
            return dialogResult;
        }

    }
}
